// server/server.js
import dotenv from "dotenv";
dotenv.config();

import fs from "fs";
import path from "path";
import express from "express";
import cors from "cors";
import puppeteer from "puppeteer"; // full puppeteer package (bundled Chromium)
import OpenAI from "openai";
import { analyzeWebsite } from "../lib/analyze.mjs";
import { fileURLToPath } from "url";

const app = express();
app.use(express.json());

// Allow from all origins while testing. Change to your frontend in production.
const FRONTEND = process.env.FRONTEND_URL || "*";
app.use(cors({ origin: FRONTEND }));

// ES module dirname fix
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Global safety: don't let unhandled rejections crash the process
process.on("unhandledRejection", (reason) => {
  console.warn("⚠️ Unhandled promise rejection:", reason);
});

// simple converter for LLM text -> minimal HTML
function textToHTML(text = "") {
  const lines = text.split("\n");
  let html = "";
  let inList = false;
  for (let line of lines) {
    line = line.trim();
    if (!line) continue;
    // strip common markdown
    line = line.replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1").replace(/`(.*?)`/g, "$1");
    if (/^-/.test(line)) {
      if (!inList) { html += "<ul>"; inList = true; }
      html += `<li>${line.replace(/^- /, "")}</li>`;
      continue;
    }
    if (inList) { html += "</ul>"; inList = false; }
    html += `<p>${line}</p>`;
  }
  if (inList) html += "</ul>";
  return html;
}

// Log incoming requests
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url} - Origin: ${req.headers.origin}`);
  next();
});

// ----------------- /analyze -----------------
app.post("/analyze", async (req, res) => {
  try {
    const { url } = req.body;
    if (!url) return res.status(400).json({ error: "URL is required" });

    // analyzeWebsite will attempt to use Puppeteer (bundled Chromium) internally
    const result = await analyzeWebsite(url);
    res.json(result);
  } catch (err) {
    console.error("Analysis Error:", err);
    res.status(500).json({ error: err?.message || "Analysis failed" });
  }
});

// ----------------- /report-pdf -----------------
app.post("/report-pdf", async (req, res) => {
  try {
    const { data } = req.body;
    if (!data) return res.status(400).json({ error: "Missing analysis JSON" });

    const prompt = `
You are a professional website auditor.
Write a detailed audit report based on this JSON:

${JSON.stringify(data, null, 2)}

Include sections:
Executive Summary
SEO Findings
Accessibility Review
Performance Review
Critical Issues
Actionable Recommendations

Write in professional tone, plain text, no markdown.
`;

    // Use OpenAI client but point to Hugging Face router via baseURL and HF key (you already used this)
    const client = new OpenAI({
      baseURL: process.env.HF_ROUTER_BASEURL || "https://router.huggingface.co/v1",
      apiKey: process.env.HUGGINGFACE_API_KEY,
    });

    const model = process.env.HF_MODEL || "meta-llama/Llama-3.1-8B-Instruct:novita";

    const response = await client.chat.completions.create({
      model,
      messages: [{ role: "user", content: prompt }],
      max_tokens: 1800,
    });

    const reportText = response.choices?.[0]?.message?.content?.trim() || "No content generated by LLM.";
    const formattedHTML = textToHTML(reportText);

    // load template and inject
    const templatePath = path.join(__dirname, "../server/templates/report.html");
    let html = fs.readFileSync(templatePath, "utf8");
    html = html.replace("{{url}}", data.url || "")
               .replace("{{date}}", new Date().toLocaleDateString())
               .replace("{{{reportText}}}", formattedHTML);

    // Puppeteer launch: prefer bundled Chromium if installed during build; fallback: do not set executablePath
    // If you want to force a system binary, set CHROME_PATH in Render env.
    const execPathFromEnv = process.env.CHROME_PATH;
    const tryExecPath = execPathFromEnv || (puppeteer.executablePath ? puppeteer.executablePath() : null);
    const useExecPath = tryExecPath && fs.existsSync(tryExecPath) ? tryExecPath : undefined;

    console.log("Puppeteer execPath candidate:", tryExecPath, "exists:", !!useExecPath);

    const browser = await puppeteer.launch({
      headless: true,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--single-process",
        "--no-zygote",
      ],
      ...(useExecPath ? { executablePath: useExecPath } : {}),
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: 0, bottom: 0, left: 0, right: 0 },
    });

    await browser.close();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=Website_Audit.pdf`);
    res.send(pdfBuffer);
  } catch (error) {
    console.error("PDF Generation Error:", error);
    // Helpful error for Render / Puppeteer issues
    if (error.message && error.message.includes("Could not find Chrome")) {
      return res.status(500).json({
        error: "Chromium not found. Ensure 'npx puppeteer install' ran during build or set CHROME_PATH env var to a valid Chrome/Chromium binary.",
        details: error.message,
      });
    }
    res.status(500).json({ error: "Failed to generate PDF", details: error?.message || error });
  }
});

// small health endpoint so root returns JSON
app.get("/", (_req, res) => res.json({ ok: true }));

const PORT = process.env.PORT || 4000;
app.listen(PORT, () => console.log(`✅ Analyzer backend running on port ${PORT}`));
